version: '3'
services: 
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017

  tika:
    container_name: tika
    build: .
    image: tika-local
    restart: on-failure
    ports:
      - 9998:9998
      # volumes:
      #   - type: bind
      #     source: ./data
      #     target: /home/user